### ISSUE TITLE
Need help execution of >>>oops = DiscreteUniform('oops', lower=0, upper=10)

### ISSUE THREAD

**Issue by shirishr** [fonnesbeck/PyMC3_DataScienceLA#2]
Execution of >>>>oops = DiscreteUniform('oops', lower=0, upper=10)
results into an error. Trace reproduced below (My environment is windows 10 with 1 GPU (i.e. gpu0) Python version 3.5:
Any idea how to resolve this?
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
C:\Anaconda3\envs\py35\lib\site-packages\pymc3\model.py in get_context(cls)
    134         try:
--> 135             return cls.get_contexts()[-1]
    136         except IndexError:

IndexError: list index out of range

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
C:\Anaconda3\envs\py35\lib\site-packages\pymc3\distributions\distribution.py in __new__(cls, name, *args, **kwargs)
     26         try:
---> 27             model = Model.get_context()
     28         except TypeError:

C:\Anaconda3\envs\py35\lib\site-packages\pymc3\model.py in get_context(cls)
    136         except IndexError:
--> 137             raise TypeError("No context on context stack")
    138 

TypeError: No context on context stack

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-10-594a3234e882> in <module>()
----> 1 oops = DiscreteUniform('oops', lower=0, upper=10)

C:\Anaconda3\envs\py35\lib\site-packages\pymc3\distributions\distribution.py in __new__(cls, name, *args, **kwargs)
     27             model = Model.get_context()
     28         except TypeError:
---> 29             raise TypeError("No model on context stack, which is needed to "
     30                             "use the Normal('x', 0,1) syntax. "
     31                             "Add a 'with model:' block")

TypeError: No model on context stack, which is needed to use the Normal('x', 0,1) syntax. Add a 'with model:' block

**Comment by fonnesbeck** [comment]
That line is supposed to fail, as a demonstration of variable instantiation. Please read the associated text in the notebook.

**Comment by shirishr** [comment]
I see what you mean.  I guess I had a senior moment there. Duh ! 💯 😉
