### ISSUE TITLE
Intro to PyMC3 Notebook Error

### ISSUE THREAD

**Issue by diehl** [fonnesbeck/PyMC3_DataScienceLA#3]
Just tried running the first notebook after creating and activating the specified conda environment. Seeing the following issue:

![pymc3](https://user-images.githubusercontent.com/349843/29234332-12a5bf66-7eab-11e7-9fef-f4c1776ff5db.jpg)

**Comment by diehl** [comment]
@fonnesbeck Is this tutorial now sufficiently out of date that it's worth looking elsewhere to learn the latest form of PyMC3?

**Comment by fonnesbeck** [comment]
That particular issue is due to the fact that the data import step in the cell above was not executed. Note that in the `%load` statement, executing the cell merely loads the code into the cell; you need to then execute the imported code to have the data loaded. Sorry for the confusion.

**Comment by diehl** [comment]
Ah ok, got it. Thanks!

**Comment by fonnesbeck** [comment]
Regarding recency of content, this is not *too* old, though we now have some updated documentation on the PyMC3 website, including [this tutorial](http://pymc-devs.github.io/pymc3/notebooks/getting_started.html). We are presently running a series of "docathons" among the development team to beef up the documentation, so more support material is forthcoming.

Another good place to learn is by looking at the directory of [notebooks](https://github.com/pymc-devs/pymc3/tree/master/docs/source/notebooks) in the repository. Several among them are pretty well-developed walk-throughs of a number of topics.

**Comment by diehl** [comment]
@fonnesbeck super helpful - thanks Chris!
